//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_pointingThere_StartRepetition;
        
        private static SteamVR_Action_Boolean p_pointingThere_StopRepetition;
        
        private static SteamVR_Action_Pose p_pointingThere_Pose;
        
        private static SteamVR_Action_Boolean p_pointingThere_NextCalibration;
        
        public static SteamVR_Action_Boolean pointingThere_StartRepetition
        {
            get
            {
                return SteamVR_Actions.p_pointingThere_StartRepetition.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean pointingThere_StopRepetition
        {
            get
            {
                return SteamVR_Actions.p_pointingThere_StopRepetition.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose pointingThere_Pose
        {
            get
            {
                return SteamVR_Actions.p_pointingThere_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean pointingThere_NextCalibration
        {
            get
            {
                return SteamVR_Actions.p_pointingThere_NextCalibration.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.pointingThere_StartRepetition,
                    SteamVR_Actions.pointingThere_StopRepetition,
                    SteamVR_Actions.pointingThere_Pose,
                    SteamVR_Actions.pointingThere_NextCalibration};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.pointingThere_StartRepetition,
                    SteamVR_Actions.pointingThere_StopRepetition,
                    SteamVR_Actions.pointingThere_Pose,
                    SteamVR_Actions.pointingThere_NextCalibration};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.pointingThere_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.pointingThere_StartRepetition,
                    SteamVR_Actions.pointingThere_StopRepetition,
                    SteamVR_Actions.pointingThere_NextCalibration};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.pointingThere_StartRepetition,
                    SteamVR_Actions.pointingThere_StopRepetition,
                    SteamVR_Actions.pointingThere_NextCalibration};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_pointingThere_StartRepetition = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PointingThere/in/StartRepetition")));
            SteamVR_Actions.p_pointingThere_StopRepetition = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PointingThere/in/StopRepetition")));
            SteamVR_Actions.p_pointingThere_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/PointingThere/in/Pose")));
            SteamVR_Actions.p_pointingThere_NextCalibration = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/PointingThere/in/NextCalibration")));
        }
    }
}
