//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PointingThere : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean StartRepetition
        {
            get
            {
                return SteamVR_Actions.pointingThere_StartRepetition;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopRepetition
        {
            get
            {
                return SteamVR_Actions.pointingThere_StopRepetition;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.pointingThere_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean NextCalibration
        {
            get
            {
                return SteamVR_Actions.pointingThere_NextCalibration;
            }
        }
    }
}
